"""Environment Perception Agent for ASE-MTAGE.

The agent builds reward-safe task/env manifests. In paper-mode LLM runs set
fallback_on_error=False so an LLM failure fails fast instead of silently becoming
a deterministic manifest.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ase_mtage.llm_client import LLMClient, extract_json_object, load_prompt
from ase_mtage.utils.io import ensure_dir, save_json, save_text


COARSE_OUTCOME_LABELS = ["early_failure", "low_progress_survival", "partial_progress", "success_like", "ambiguous"]


@dataclass(slots=True)
class EnvPerceptionArtifacts:
    task_manifest_path: Path
    env_manifest_path: Path
    outcome_label_schema_path: Path
    feature_schema_path: Path


class EnvPerceptionAgent:
    """Create sanitized task/env manifests without exposing official reward code."""

    def __init__(self, output_core_dir: str | Path, *, llm_client: LLMClient | None = None, temperature: float = 0.2, fallback_on_error: bool = True) -> None:
        self.output_core_dir = ensure_dir(output_core_dir)
        self.llm_client = llm_client
        self.temperature = temperature
        self.fallback_on_error = fallback_on_error

    def run(self, *, env_id: str, task_description: str | None = None, sanitized_env_summary: dict[str, Any] | None = None) -> EnvPerceptionArtifacts:
        task_goal = task_description or self._default_task_goal(env_id)
        if self.llm_client is not None:
            try:
                manifest = self._build_llm_manifest(env_id=env_id, task_goal=task_goal, sanitized_env_summary=sanitized_env_summary or {})
            except Exception as exc:
                save_text(self.output_core_dir / "env_perception_llm_error.txt", str(exc) + "\n")
                if not self.fallback_on_error:
                    raise RuntimeError("EnvPerceptionAgent LLM failed and fallback_on_error=false") from exc
                manifest = self.build_env_manifest(env_id=env_id, task_goal=task_goal, sanitized_env_summary=sanitized_env_summary)
        else:
            manifest = self.build_env_manifest(env_id=env_id, task_goal=task_goal, sanitized_env_summary=sanitized_env_summary)
        manifest["official_reward_visible"] = False
        manifest.setdefault("coarse_outcome_labels", COARSE_OUTCOME_LABELS)
        manifest.setdefault("labeling_cautions", ["Do not use or infer the official environment reward."])
        manifest.setdefault("trajectory_features_to_extract", ["episode_length", "terminated", "truncated", "progress_improvement", "reward_component_totals"])
        manifest["llm_used"] = bool(self.llm_client is not None and not (self.output_core_dir / "env_perception_llm_error.txt").exists())

        task_manifest_text = self._build_task_manifest_md(manifest)
        task_manifest_path = save_text(self.output_core_dir / "task_manifest.md", task_manifest_text)
        env_manifest_path = save_json(self.output_core_dir / "env_manifest.json", manifest)
        outcome_label_schema_path = save_json(
            self.output_core_dir / "outcome_label_schema.json",
            {
                "coarse_outcome_labels": COARSE_OUTCOME_LABELS,
                "label_definitions": {
                    "early_failure": "Episode ends early with little useful progress.",
                    "low_progress_survival": "Episode lasts but shows little task progress.",
                    "partial_progress": "Trajectory shows real progress but does not reach stable success.",
                    "success_like": "Trajectory strongly matches the task goal according to observable evidence.",
                    "ambiguous": "Evidence is insufficient or conflicting.",
                },
                "official_reward_visible": False,
            },
        )
        feature_schema_path = save_json(
            self.output_core_dir / "feature_schema.json",
            {"trajectory_features_to_extract": manifest["trajectory_features_to_extract"], "notes": "Generated by EnvPerceptionAgent from sanitized environment evidence."},
        )
        return EnvPerceptionArtifacts(task_manifest_path, env_manifest_path, outcome_label_schema_path, feature_schema_path)

    def _build_llm_manifest(self, *, env_id: str, task_goal: str, sanitized_env_summary: dict[str, Any]) -> dict[str, Any]:
        template = load_prompt("env_perception.md")
        input_artifacts = {"env_id": env_id, "user_task_description": task_goal, "sanitized_env_source_or_summary": sanitized_env_summary, "reward_leakage_policy": "official reward logic is redacted and forbidden"}
        user_prompt = template.replace("{input_artifacts}", json.dumps(input_artifacts, ensure_ascii=False, indent=2))
        save_text(self.output_core_dir / "env_perception_prompt.txt", user_prompt)
        resp = self.llm_client.chat(system_prompt="You are the ASE-MTAGE Env Perception Agent. Output only valid JSON.", user_prompt=user_prompt, temperature=self.temperature, agent_name="env_perception")
        save_text(self.output_core_dir / "env_perception_response.txt", resp.content)
        save_json(self.output_core_dir / "env_perception_raw_response.json", resp.raw)
        return extract_json_object(resp.content)

    def build_env_manifest(self, *, env_id: str, task_goal: str, sanitized_env_summary: dict[str, Any] | None = None) -> dict[str, Any]:
        obs_schema = self._generic_observation_schema(env_id)
        action_schema = self._generic_action_schema(env_id)
        summary = sanitized_env_summary or {}
        return {
            "env_name": env_id,
            "task_goal": task_goal,
            "official_reward_visible": False,
            "observation_space": summary.get("observation_space"),
            "action_space_raw": summary.get("action_space"),
            "max_episode_steps": summary.get("max_episode_steps"),
            "observation_schema": obs_schema,
            "action_schema": action_schema,
            "termination_signals": ["terminated indicates an environment terminal event; classify using observable final-state evidence.", "truncated indicates a time-limit or max-episode-step cutoff."],
            "available_info_keys": summary.get("info_keys", []),
            "trajectory_features_to_extract": ["episode_length", "max_episode_steps", "terminated", "truncated", "initial_progress_proxy", "final_progress_proxy", "progress_improvement", "final_state_summary", "action_usage_summary", "reward_component_totals"],
            "coarse_outcome_labels": COARSE_OUTCOME_LABELS,
            "labeling_cautions": ["Do not use or infer the official environment reward.", "Do not treat long episode length alone as success_like.", "Do not treat high progress with unstable terminal evidence as success_like.", "Use ambiguous when observable evidence is insufficient or conflicting."],
            "sanitizer_warnings": summary.get("warnings", []),
        }

    def _default_task_goal(self, env_id: str) -> str:
        name = env_id.lower()
        if "lunarlander" in name:
            return "land safely on the landing pad using observable state evidence, without using the official reward"
        if "bipedalwalker" in name:
            return "move forward with a stable gait while avoiding falls, without using the official reward"
        if "cartpole" in name:
            return "keep the pole balanced for as long as possible, without using the official reward"
        return "complete the task using observable state and outcome evidence, without using the official reward"

    def _generic_observation_schema(self, env_id: str) -> list[dict[str, Any]]:
        name = env_id.lower()
        if "lunarlander" in name:
            names = ["x_position", "y_position", "x_velocity", "y_velocity", "angle", "angular_velocity", "left_leg_contact", "right_leg_contact"]
            return [{"index": i, "name": n, "meaning": n.replace("_", " "), "used_for_labeling": True} for i, n in enumerate(names)]
        if "cartpole" in name:
            names = ["cart_position", "cart_velocity", "pole_angle", "pole_angular_velocity"]
            return [{"index": i, "name": n, "meaning": n.replace("_", " "), "used_for_labeling": True} for i, n in enumerate(names)]
        if "bipedalwalker" in name:
            names = ["hull_angle", "hull_angular_velocity", "hull_horizontal_velocity", "hull_vertical_velocity", "hip1_angle", "hip1_speed", "knee1_angle", "knee1_speed", "leg1_ground_contact", "hip2_angle", "hip2_speed", "knee2_angle", "knee2_speed", "leg2_ground_contact"]
            return [{"index": i, "name": n, "meaning": n.replace("_", " "), "used_for_labeling": True} for i, n in enumerate(names)] + [{"index": "14+", "name": "lidar_readings", "meaning": "terrain lidar observations", "used_for_labeling": False}]
        return [{"index": "unknown", "name": "observation_vector", "meaning": "environment observation vector; specialize via env adapter", "used_for_labeling": True}]

    def _generic_action_schema(self, env_id: str) -> list[dict[str, Any]]:
        name = env_id.lower()
        if "lunarlander" in name:
            return [{"id": i, "meaning": m} for i, m in enumerate(["do nothing", "fire left engine", "fire main engine", "fire right engine"])]
        if "cartpole" in name:
            return [{"id": 0, "meaning": "push cart left"}, {"id": 1, "meaning": "push cart right"}]
        if "bipedalwalker" in name:
            return [{"id": 0, "meaning": "hip1 motor"}, {"id": 1, "meaning": "knee1 motor"}, {"id": 2, "meaning": "hip2 motor"}, {"id": 3, "meaning": "knee2 motor"}]
        return [{"id": "unknown", "meaning": "environment action; specialize via env adapter"}]

    def _build_task_manifest_md(self, manifest: dict[str, Any]) -> str:
        labels = "\n".join(f"- `{x}`" for x in manifest.get("coarse_outcome_labels", COARSE_OUTCOME_LABELS))
        features = "\n".join(f"- `{x}`" for x in manifest.get("trajectory_features_to_extract", []))
        cautions = "\n".join(f"- {x}" for x in manifest.get("labeling_cautions", []))
        return f"""# Task Manifest

## Environment

`{manifest.get('env_name')}`

## Task Goal

{manifest.get('task_goal')}

## Reward Leakage Policy

Official environment reward is not visible and must not be used.

## Coarse Outcome Labels

{labels}

## Trajectory Features To Extract

{features}

## Labeling Cautions

{cautions}
"""
